# 服务端口
server:
  port: 8201
# 服务名
spring:
  application:
    name: service-user

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jsyy_user?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lzq2686105


  # mongodb配置
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: jsyy

  # json数据配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000

  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: 101.35.181.165:8848

    # sentinel配置
    sentinel:
      transport:
        dashboard: 101.35.181.165:8858

  # rabbitmq地址
  rabbitmq:
    host: 101.35.181.165
    port: 5672
    username: root
    password: root

  # 允许存在多个Feign调用相同Service的接口
  main:
    allow-bean-definition-overriding: true

# mapper.xml路径配置
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# openfeign配置sentinel
feign:
  sentinel:
    enabled: true
